/**
 * vmix_script_save - Save a VB.NET script to a file
 *
 * Since vMix API doesn't support adding scripts to the UI programmatically,
 * this tool saves scripts to a .txt file that can be manually imported into vMix.
 * Also optionally copies to clipboard for easy pasting.
 */

import { z } from 'zod';
import { createTool, successResult, errorResult, type ToolContext } from '../base.js';
import { validateVmixScript } from '../../validation/script-validator.js';
import * as fs from 'fs/promises';
import * as path from 'path';
import { spawn } from 'child_process';

function copyWithCommand(command: string, args: string[], text: string): Promise<boolean> {
  return new Promise((resolve) => {
    const proc = spawn(command, args, { stdio: ['pipe', 'ignore', 'ignore'] });
    let settled = false;

    const finish = (success: boolean) => {
      if (!settled) {
        settled = true;
        resolve(success);
      }
    };

    proc.once('error', () => finish(false));
    proc.once('close', (code) => finish(code === 0));
    proc.stdin.once('error', () => finish(false));
    proc.stdin.end(text);
  });
}

/**
 * Copy text to clipboard (Windows/Mac/Linux)
 */
async function copyToClipboard(text: string): Promise<boolean> {
  try {
    const platform = process.platform;

    if (platform === 'win32') {
      return await copyWithCommand('clip', [], text);
    }

    if (platform === 'darwin') {
      return await copyWithCommand('pbcopy', [], text);
    }

    return (
      (await copyWithCommand('xclip', ['-selection', 'clipboard'], text)) ||
      (await copyWithCommand('xsel', ['--clipboard', '--input'], text))
    );
  } catch {
    return false;
  }
}

export const saveScriptTool = createTool({
  name: 'vmix_script_save',
  description:
    'Save a VB.NET script to a file for later use. ' +
    'Scripts are saved as .txt files (vMix import format) to "Documents/vmix-scripts". ' +
    'Optionally copies to clipboard for easy pasting into vMix. ' +
    'The script is validated before saving.',
  schema: z.object({
    name: z
      .string()
      .describe(
        'Name for the script file (without extension). ' +
          'Example: "camera-cycle" creates "camera-cycle.txt"'
      ),
    code: z.string().describe('The VB.NET script code to save'),
    copy_to_clipboard: z
      .boolean()
      .default(true)
      .describe('Copy the script to clipboard for easy pasting into vMix. Default: true'),
    overwrite: z
      .boolean()
      .default(false)
      .describe('If true, overwrite existing file. Default: false'),
  }),
  handler: async (
    {
      name,
      code,
      copy_to_clipboard,
      overwrite,
    }: { name: string; code: string; copy_to_clipboard: boolean; overwrite: boolean },
    _ctx: ToolContext
  ) => {
    // Validate the script first
    const validation = validateVmixScript(code);
    if (!validation.valid && validation.errors.length > 0) {
      const errorMessages = validation.errors.map((e) => `- ${e}`).join('\n');
      return errorResult(
        `Script validation failed - not saved:\n\n${errorMessages}\n\nFix these issues and try again.`
      );
    }

    // Sanitize filename
    const safeName = name.replace(/[<>:"/\\|?*]/g, '-').trim();
    if (!safeName) {
      return errorResult('Invalid script name. Use alphanumeric characters and dashes.');
    }

    // Determine save directory (Documents/vmix-scripts)
    const homeDir = process.env.USERPROFILE ?? process.env.HOME ?? '.';
    const scriptsDir = path.join(homeDir, 'Documents', 'vmix-scripts');

    // Ensure directory exists
    try {
      await fs.mkdir(scriptsDir, { recursive: true });
    } catch {
      // Directory might already exist, that's fine
    }

    // Use .txt extension (vMix import format)
    const filePath = path.join(scriptsDir, `${safeName}.txt`);

    // Check if file exists
    try {
      await fs.access(filePath);
      if (!overwrite) {
        return errorResult(
          `Script "${safeName}.txt" already exists in ${scriptsDir}. ` +
            'Set overwrite=true to replace it, or use a different name.'
        );
      }
    } catch {
      // File doesn't exist, that's what we want
    }

    const header = `' vMix Script: ${safeName}
' Generated by CueScope
' Date: ${new Date().toISOString().split('T')[0]}
'
' To import into vMix:
' 1. Open vMix Settings -> Scripting
' 2. Click "Add Script" -> Import
' 3. Select this .txt file
' =========================================================

`;

    const fullScript = header + code;

    try {
      await fs.writeFile(filePath, fullScript, 'utf-8');
    } catch (e) {
      return errorResult(`Failed to save script: ${e instanceof Error ? e.message : 'Unknown error'}`);
    }

    let clipboardStatus = '';
    if (copy_to_clipboard) {
      const copied = await copyToClipboard(code);
      clipboardStatus = copied
        ? '\n\nScript copied to clipboard - paste directly into vMix script editor.'
        : '\n\nCould not copy to clipboard (clipboard access unavailable).';
    }

    let message = `Script saved to:\n${filePath}${clipboardStatus}\n\n`;
    message += 'To import into vMix:\n';
    message += '1. Open vMix -> Settings -> Scripting\n';
    message += '2. Click "Add Script" -> Import\n';
    message += '3. Select the .txt file\n';
    message += '\nOr paste from clipboard into a new script.';

    if (validation.warnings.length > 0) {
      message += `\n\nWarnings:\n${validation.warnings.map((w) => `- ${w}`).join('\n')}`;
    }

    return successResult(message);
  },
});
